apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-6urh
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-6urh
    app.kubernetes.io/part-of: tkrw-pr712-0075-0054-app
  name: devfile-sample-6urh
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-6urh
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-6urh
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0054-tenant/tkrw-pr712-0075-0054-app/devfile-sample-6urh@sha256:5c79a8cb51e47c7cdddfbe692087bbc0ba49e2ac84208de66091494e4f286ffd
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
